import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import { QueryProvider } from "@/components/query-client";
import { JotaiProvider } from "@/components/jotai-provider";
import { Modals } from "@/components/modals";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import Script from "next/script";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    initMap: () => void;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <ThemeProvider attribute={`class`} defaultTheme="light">
          <JotaiProvider>
            <QueryProvider>
              <SessionProvider>
                <NextSSRPlugin
                  /**
                   * The `extractRouterConfig` will extract **only** the route configs
                   * from the router to prevent additional information from being
                   * leaked to the client. The data passed to the client is the same
                   * as if you were to fetch `/api/uploadthing` directly.
                   */
                  routerConfig={extractRouterConfig(ourFileRouter)}
                />
                {children} <Modals />
              </SessionProvider>
            </QueryProvider>
          </JotaiProvider>
        </ThemeProvider>
        <Script
          defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCrqWirugbW4DkliahG3rN8BzdI7SkrYnU&libraries=places&callback=initMap"
        ></Script>
      </body>
    </html>
  );
}
